//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/RenamedAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/RenamedAction.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @RenamedAction: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @RenamedAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""RenamedAction"",
    ""maps"": [
        {
            ""name"": ""FlatMap"",
            ""id"": ""25b7df9d-74e5-45fe-b3d6-d005638701dd"",
            ""actions"": [
                {
                    ""name"": ""KeyShoot"",
                    ""type"": ""Button"",
                    ""id"": ""cafa7916-079f-4c83-933b-e5b071f62bbc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ClickShoot"",
                    ""type"": ""Button"",
                    ""id"": ""1970feb3-cf33-4754-8aa7-bd148cbb593a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4781e065-5745-43ff-abc4-af9f1de1bd71"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";MouseScheme"",
                    ""action"": ""ClickShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a85ae01-77d0-4b04-989a-6d95203b612c"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Board"",
                    ""action"": ""KeyShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // FlatMap
        m_FlatMap = asset.FindActionMap("FlatMap", throwIfNotFound: true);
        m_FlatMap_KeyShoot = m_FlatMap.FindAction("KeyShoot", throwIfNotFound: true);
        m_FlatMap_ClickShoot = m_FlatMap.FindAction("ClickShoot", throwIfNotFound: true);
    }

    ~@RenamedAction()
    {
        UnityEngine.Debug.Assert(!m_FlatMap.enabled, "This will cause a leak and performance issues, RenamedAction.FlatMap.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // FlatMap
    private readonly InputActionMap m_FlatMap;
    private List<IFlatMapActions> m_FlatMapActionsCallbackInterfaces = new List<IFlatMapActions>();
    private readonly InputAction m_FlatMap_KeyShoot;
    private readonly InputAction m_FlatMap_ClickShoot;
    /// <summary>
    /// Provides access to input actions defined in input action map "FlatMap".
    /// </summary>
    public struct FlatMapActions
    {
        private @RenamedAction m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public FlatMapActions(@RenamedAction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "FlatMap/KeyShoot".
        /// </summary>
        public InputAction @KeyShoot => m_Wrapper.m_FlatMap_KeyShoot;
        /// <summary>
        /// Provides access to the underlying input action "FlatMap/ClickShoot".
        /// </summary>
        public InputAction @ClickShoot => m_Wrapper.m_FlatMap_ClickShoot;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_FlatMap; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="FlatMapActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(FlatMapActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="FlatMapActions" />
        public void AddCallbacks(IFlatMapActions instance)
        {
            if (instance == null || m_Wrapper.m_FlatMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FlatMapActionsCallbackInterfaces.Add(instance);
            @KeyShoot.started += instance.OnKeyShoot;
            @KeyShoot.performed += instance.OnKeyShoot;
            @KeyShoot.canceled += instance.OnKeyShoot;
            @ClickShoot.started += instance.OnClickShoot;
            @ClickShoot.performed += instance.OnClickShoot;
            @ClickShoot.canceled += instance.OnClickShoot;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="FlatMapActions" />
        private void UnregisterCallbacks(IFlatMapActions instance)
        {
            @KeyShoot.started -= instance.OnKeyShoot;
            @KeyShoot.performed -= instance.OnKeyShoot;
            @KeyShoot.canceled -= instance.OnKeyShoot;
            @ClickShoot.started -= instance.OnClickShoot;
            @ClickShoot.performed -= instance.OnClickShoot;
            @ClickShoot.canceled -= instance.OnClickShoot;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="FlatMapActions.UnregisterCallbacks(IFlatMapActions)" />.
        /// </summary>
        /// <seealso cref="FlatMapActions.UnregisterCallbacks(IFlatMapActions)" />
        public void RemoveCallbacks(IFlatMapActions instance)
        {
            if (m_Wrapper.m_FlatMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="FlatMapActions.AddCallbacks(IFlatMapActions)" />
        /// <seealso cref="FlatMapActions.RemoveCallbacks(IFlatMapActions)" />
        /// <seealso cref="FlatMapActions.UnregisterCallbacks(IFlatMapActions)" />
        public void SetCallbacks(IFlatMapActions instance)
        {
            foreach (var item in m_Wrapper.m_FlatMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FlatMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="FlatMapActions" /> instance referencing this action map.
    /// </summary>
    public FlatMapActions @FlatMap => new FlatMapActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "FlatMap" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="FlatMapActions.AddCallbacks(IFlatMapActions)" />
    /// <seealso cref="FlatMapActions.RemoveCallbacks(IFlatMapActions)" />
    public interface IFlatMapActions
    {
        /// <summary>
        /// Method invoked when associated input action "KeyShoot" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnKeyShoot(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ClickShoot" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnClickShoot(InputAction.CallbackContext context);
    }
}
